name: agile_predict
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - matplotlib
  - seaborn
  - numpy
  - pandas
  - plotly
  - scipy
  - scikit-learn
  - tables
  - xgboost
  - requests
  - pip:
    - -r backend/requirements.txt
    - black
